[project]
name = "test3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "michael", email = "michael0604.lee@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
test3 = "test3:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
